version: "3"
services:
  smoodle:
    image: smoodle
    build:
      context: ./
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://docker:secret@db:5432/docker
      PORT: 4000
      HOST_NAME: localhost
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: docker
    ports:
      - "5432:5432"
    volumes:
      - "data:/var/lib/postgresql/data"
volumes:
  data:
