version: "3"
services:
 dev_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: homestead
      POSTGRES_DB: smoodle_dev
    ports:
      - "5432:5432"
    volumes:
      - "dev_data:/var/lib/postgresql/data"
volumes:
  dev_data:
