version: "3"
services:
 db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: homestead
      POSTGRES_DB: smoodle_test
    ports:
      - "5432:5432"
    volumes:
      - "test_data:/var/lib/postgresql/data"
volumes:
  test_data:
