jobs:
  build_back_end:
    docker:
      - image: circleci/elixir:1.9.1
    environment:
      MIX_ENV: test
    steps:
      - checkout
      - restore_cache:
          key: elixir-deps-{{ .Branch }}-{ checksum "mix.lock" }}
      - run:
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
            mix compile
      - save_cache:
          key: elixir-deps-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - ./deps
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  backend_unit_tests:
    docker:
      - image: circleci/elixir:1.9.1
    environment:
      MIX_ENV: test
    steps:
      - attach_workspace:
          at: ./
      - run:
          command: |
            ls -al
            ls _build/test/lib -al
      - run: mix test --trace

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_back_end:
          filters:
            branches:
              only: master
      - backend_unit_tests:
          requires:
            - build_back_end
