jobs:
  build_back_end:
    docker:
      - image: elixir:1.9.1
    steps:
      - checkout
      - run:
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - save_cache:
          key: elixir-deps-{{ checksum "mix.lock" }}
          paths:
            - ~/deps

  backend_unit_tests:
    docker:
      - image: elixir:1.9.1
    steps:
      - checkout
      - restore_cache:
          key: elixir-deps-{{ checksum "mix.lock" }}
      - run: mix compile

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_back_end:
          filters:
            branches:
              only: master
      - backend_unit_tests:
          requires:
            - build_back_end
